### ISSUE TITLE
Unable to reflect background color of selected date.

### ISSUE THREAD

**Issue by irajsuhail** [dilipchandima/rn-select-date-range#2]
Hi, first of all, thank you for the wonderful project.

While using the `DateRangePicker` component, when I try to set the background color of the `selectedDateStyle` to any other color it still reflects red color in the app.

**Comment by dilipchandima** [comment]
Thanks for using my date range selector 

Can you try to use in following manner 

`selectedDateContainerStyle` => for selected container styles 
`selectedDateStyle` => for selected Text style

**Comment by irajsuhail** [comment]
Yep, tried it in the same way but still the same result.

**Comment by irajsuhail** [comment]
Sorry, The package version was mishandled at the time of install. The `rn-select-date-range v2.0.0` works as expected 👍🏻
