### ISSUE TITLE
Too many days showing

### ISSUE THREAD

**Issue by maartenvandillen** [dilipchandima/rn-select-date-range#3]
Hi thanks for this nice component. When scrolling back and forward through the months I get additional duplicate dates showing incorrectly. Also a warning of two children with the same key. See screenshot.

![image](https://user-images.githubusercontent.com/6582935/131806465-7a43795a-4f53-4ea3-bcdc-1a8d73f58321.png)

**Comment by dilipchandima** [comment]
@maartenvandillen thanks for letting us know :)  let us fix this and let you know.

**Comment by maartenvandillen** [comment]
Thanks. No hurry though, I've decided to make my own component instead since I need to select multiple months and don't really need the day selection feature. I still might use this component in another project once this is fixed.

**Comment by dilipchandima** [comment]
Fixed the issue and release 2.1.0
